[project]
name = "glove80"
version = "0.1.0"
description = "VimGram - Glove80 keyboard layout"
authors = [{name = "miguelcsilva"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keymap-drawer",
]
