[tool.poetry]
name = "glove80"
version = "0.1.0"
description = ""
authors = ["miguelcsilva"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
keymap-drawer = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
